apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "detector-storageclass"