apiVersion: v1
kind: Service
metadata:
  name: detector-yolo-service
  #namespace: detector
  labels:
    app: detector-yolo
spec:
  selector:
    app: detector-yolo
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22